// Generated by https://quicktype.io
import { ResponseGeneric } from "../common/response.interface";

export interface ResponseCharacter {
    get_all_character: ResponseGeneric<CharacterDB>;
}

export interface CharacterDB {
    name: string;
    specie: SpecieDB;
    img: string;
    id: string;
}

export interface SpecieDB {
    name: Name;
}

export enum Name {
    Alien = "Alien",
    Human = "Human",
}
